controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home_1
  - group: gripper
    pose: open